config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :tags
    resources :users
    resources :searches do
      collection do
        get "search"
      end
    end
  end

  # ユーザー
  scope module: :public do
    resources :users
    resources :boardgames
    resources :records
    resources :players
    resources :searches do
      collection do
        get "search"
      end
    end
    resources :bucket_lists do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    root to: "homes#top"
  end

  # ゲスト
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_game.rb
# frozen_string_literal: true

class BoardGame < ApplicationRecord
  belongs_to :user
  has_many :records, dependent: :destroy
end

app/models/bucket_list.rb
# frozen_string_literal: true

class BucketList < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bucket_list_tag_relations, dependent: :destroy
  has_many :tags, through: :bucket_list_tag_relations, dependent: :destroy

  # 一致するレコードが存在しない＝「まだいいねしていない→createアクションへ」
  # 一致するレコードが存在する　＝「すでにいいね済み→destroyアクションへ」
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索
  def self.looks(word)
    if word.blank?
      BucketList.all
    else
      BucketList.where("bucket_title LIKE?", "%#{word}%")
    end
  end

  # def save_tag(sent_tags)
  #   sent_tags.each do |new|
  #     new_bucket_list_tag = Tag.find_or_create_by(name: new)
  #     self.tags << new_bucket_list_tag
  #   end
  # end

  accepts_nested_attributes_for :bucket_list_tag_relations
  validates :memo, presence: true, length: { maximum: 140 }
end

app/models/bucket_list_tag_relation.rb
# frozen_string_literal: true

class BucketListTagRelation < ApplicationRecord
  belongs_to :bucket_list
  belongs_to :tag
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bucket_list

  validates :comment, presence: true, length: { maximum: 400 }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :bucket_list
  belongs_to :user
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :user
  has_many :scores
  has_many :records, through: :scores

  validates :player_name, length: { maximum: 12 }, presence: true
end

app/models/record.rb
# frozen_string_literal: true

class Record < ApplicationRecord
  belongs_to :user
  belongs_to :board_game
  has_many :scores
  has_many :players, through: :scores

  # score(子モデル)を保存するためのフォーム
  accepts_nested_attributes_for :scores, allow_destroy: true

  validates :memo, length: { maximum: 400 }
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  belongs_to :record
  belongs_to :player

  validates :score, numericality: {only_integer: true}
  
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :bucket_list_tag_relations, dependent: :destroy, foreign_key: "tag_id"
  has_many :bucket_lists, through: :bucket_list_tag_relations, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_games, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :bucket_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  # プロフィール画像
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-mage.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索
  def self.looks(word)
    if word.blank?
      User.all
    else
      User.where("name LIKE?", "%#{word}%")
    end
  end

  # ゲストユーザー
  def self.guest
    find_or_create_by!(name: "guestuser",
                      email: "guests@example.com",
                      postal_code: "1231234",
                      prefecture: "ボドゲ県",
                      city: "ミープル区",
                      age: "0〜99",
                      memo: "主に重ゲーを遊んでいます！") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  validates :postal_code, presence: true
  validates :name, uniqueness: true, length: { maximum: 12 }
  validates :city, presence: true
  validates :age, presence: true
end

app/controllers/admin/searches_controller.rb
# frozen_string_literal: true

class Admin::SearchesController < ApplicationController
  before_action :require_permission

  def search
    if params[:address_num] == "1" # ユーザーを検索
      @users = User.looks(params[:word])
    elsif params[:address_num] == "2" # ユーザーのバゲットリストを検索
      @bucket_lists = BucketList.looks(params[:word])
    end
    render :index
  end

  def require_permission
    if admin_signed_in?
    else
      redirect_to new_admin_session_path
    end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def new
    @new_tag = Tag.new
    @tags = Tag.all
  end

  def create
    @new_tag = Tag.new(params_tag)
    @new_tag.save
    @tags = Tag.all
    redirect_to new_admin_tag_path
  end

  def destroy
    tag = Tag.find(params[:id])
    active_tag = BucketListTagRelation.where(tag_id: params[:id])
    # タグが利用中の場合削除できないように分岐
    if active_tag.blank?
      tag.destroy
    else
      flash[:tag_destroy_faild] = "利用中のタグは削除不可"
    end
    @tags = Tag.all
    redirect_to new_admin_tag_path
  end

  private
    def params_tag
      params.permit(:name)
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :postal_code, :prefecture, :city, :age])
    end

  private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_searches_path
      else
        root_path
      end
    end

    def
    after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
        root_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end
end

app/helpers/admin/searches_helper.rb
# frozen_string_literal: true

module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/guest/sessions_helper.rb
# frozen_string_literal: true

module Guest::SessionsHelper
end

app/helpers/player_helper.rb
# frozen_string_literal: true

module PlayerHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/searches/_search_form.html.erb
<div class="row mb-3">
  <%= form_with url: search_admin_searches_path, local: true, method: :get, class: "row" do |f| %>
    <div>
      <string class="pe-2">Search for?</string>
      <%= f.radio_button :address_num, 1, checked: true %><%= f.label :address_num_1, "ユーザー", class: "p-2" %>
      <%= f.radio_button :address_num, 2 %><%= f.label :address_num_2, "ユーザーの投稿", class: "p-2" %>
    </div>
    <div class="col-5">
      <%= f.text_field :word, class: "form-control" %>
    </div>
    <div class="col-auto ps-1">
      <%= f.submit "検索", class: "btn btn-outline-success" %>
    </div>
  <% end %>
</div>

app/views/admin/searches/index.html.erb
<div class="col-6 offset-md-3">
  <div class="ms-3">
    <h4>『ユーザー』または『ユーザーの投稿』を検索</h4>
    <p>※一覧したい場合、無記入で検索</p>
    <%= render "admin/searches/search_form" %>
  </div>
  <div class="ps-2">
    <h3>検索結果</h3>
    <table class="table">
      <!--ユーザーを検索した結果-->
      <% if @users.present? %>
        <tr>
          <th>ユーザー</th>
          <th>アカウント状態</th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to admin_user_path(user) do %>
                <%= image_tag user.get_profile_image(100,100) %>
                <%= user.name %>
              <% end %>
            </td>
            <td>
              <%= user.is_deleted ? '凍結中' : '有効' %>
            </td>
          </tr>
        <% end %>
      <!--bucketlistを検索した結果-->
      <% elsif @bucket_lists.present? %>
        <% @bucket_lists.each do |bucket_list| %>
          <tr>
            <!--遊びたいボドゲ情報-->
            <td width="10%">
              <img src="<%= bucket_list.image %>" width="100"/>
            </td>
            <td width="80%">
              <!--BGデータ-->
              <div class="pb-2">
                <span class="pe-2"><%= bucket_list.bucket_title %></span>
                <i class="fa-solid fa-users pe-1"></i><%= bucket_list.minplayer %>-<%= bucket_list.maxplayer %>
                <i class="fa-regular fa-clock pe-1"></i><%= bucket_list.playingtime %>
              </div>
              <!--メモ-->
              <div class="mb-4">
                <%= safe_join(bucket_list.memo.split("\n"),tag(:br)) %></br>
              </div>
              <div>
                <!--タグ-->
                <i class="fas fa-tag"></i><%= bucket_list.tags.map(&:name).join(', ') %></br>
                <!--ユーザーリンク-->
                <%= link_to admin_user_path(bucket_list.user), class: "pe-5 text-decoration-none" do %>
                  <i class="fa-solid fa-circle-user"></i><%= bucket_list.user.name %>
                <% end %>
              </div>
            </td>
            <td>
              <%= link_to admin_user_path(bucket_list, word: params[:word]), method: :delete do  %>
                <button class="btn btn-outline-danger ms-2">削除</button>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>