config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :tags
    resources :users
    resources :searches do
      collection do
        get "search"
      end
    end
  end

  # ユーザー
  scope module: :public do
    resources :users
    resources :boardgames
    resources :records
    resources :players
    resources :searches do
      collection do
        get "search"
      end
    end
    resources :bucket_lists do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    root to: "homes#top"
  end

  # ゲスト
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_games, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :bucket_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  # プロフィール画像
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-mage.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索
  def self.looks(word)
    if word.blank?
      User.all
    else
      User.where("name LIKE?", "%#{word}%")
    end
  end

  # ゲストユーザー
  def self.guest
    find_or_create_by!(name: "guestuser",
                      email: "guests@example.com",
                      postal_code: "1231234",
                      prefecture: "ボドゲ県",
                      city: "ミープル区",
                      age: "0〜99",
                      memo: "主に重ゲーを遊んでいます！") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  validates :postal_code, presence: true
  validates :name, uniqueness: true, length: { maximum: 12 }
  validates :city, presence: true
  validates :age, presence: true
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :require_permission

  def show
    @user = User.find(params[:id])
    @played_bgs = @user.board_games
    @bucket_lists = @user.bucket_lists
    @tag_list = Tag.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(is_deleted_params)
    redirect_to admin_user_path(@user)
  end

  def destroy
    bucket_list = BucketList.find(params[:id])
    bucket_list.destroy
    if params[:user].blank?
      redirect_to search_admin_searches_path(params[:word])
    else
      redirect_to admin_user_path(params[:user])
    end
  end

  def require_permission
    if admin_signed_in?
    else
      redirect_to new_admin_session_path
    end
  end

  private
    def is_deleted_params
      params.permit(:is_deleted)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/show.html.erb
<div class='col-md-4'>
  <h3>
    User
    <% if @user.is_deleted %>
      <%= link_to admin_user_path(@user, is_deleted: false), method: :put do %>
        <button class="btn btn-outline-info ms-2">解凍</button>
      <% end %>
    <% else %>
      <%= link_to admin_user_path(@user, is_deleted: true), method: :put do %>
        <button class="btn btn-outline-danger ms-2">凍結</button>
      <% end %>
    <% end %>
  </h3>
  <%= render 'public/users/user_info', user: @user %>
</div>

<div class='col-md-8'>
  <h3>User's Boardgames</h3>
  <div class="accordion" id="accordionPanelsStayOpenExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
          Played Games
        </button>
      </h2>
      <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
        <div class="accordion-body">
          <table class="table-bordered col-12">
            <% @played_bgs.each do |bg| %>
              <tr>
                <td>
                  <%= link_to boardgame_path(bg) do %>
                    <img src="<%= bg.image %>" width="100"/>
                  <% end %>
                </td>
                <td class="text-center" width="18%">
                  <%= link_to boardgame_path(bg) do %>
                    <%= bg.played_title %></br>
                    <%= bg.minplayer %>-<%= bg.maxplayer %>人</br>
                    <%= bg.playingtime %>min</br>
                  <% end %>
                </td>
                <td class="text-center" width="60%">
                  遊んだ回数:<%= bg.records.count %> 遊んだ人：
                  </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
           Bucket List
        </button>
      </h2>
      <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
        <div class="accordion-body">
          <table class="table col-md-12">
            <!--bucket_listに登録してるゲームを一覧表示-->
            <% @bucket_lists.each do |bucket_list| %>
              <tr>
                <!--遊びたいボドゲ情報-->
                <td width="10%">
                  <img src="<%= bucket_list.image %>" width="100"/>
                </td>
                <td width="80%">
                  <!--BGデータ-->
                  <div class="pb-2">
                    <span class="pe-2"><%= bucket_list.bucket_title %></span>
                    <i class="fa-solid fa-users pe-1"></i><%= bucket_list.minplayer %>-<%= bucket_list.maxplayer %>
                    <i class="fa-regular fa-clock pe-1"></i><%= bucket_list.playingtime %>
                  </div>
                  <!--メモ-->
                  <div class="mb-4">
                    <%= safe_join(bucket_list.memo.split("\n"),tag(:br)) %></br>
                  </div>
                  <div>
                    <!--タグ-->
                    <i class="fas fa-tag"></i><%= bucket_list.tags.map(&:name).join(', ') %></br>
                  </div>
                </td>
                <td>
                  <%= link_to admin_user_path(bucket_list, user: bucket_list.user), method: :delete do  %>
                    <button class="btn btn-outline-danger ms-2">削除</button>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>