config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :tags
    resources :users
    resources :searches do
      collection do
        get "search"
      end
    end
  end

  # ユーザー
  scope module: :public do
    resources :users
    resources :boardgames
    resources :records
    resources :players
    resources :searches do
      collection do
        get "search"
      end
    end
    resources :bucket_lists do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    root to: "homes#top"
  end

  # ゲスト
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_game.rb
# frozen_string_literal: true

class BoardGame < ApplicationRecord
  belongs_to :user
  has_many :records, dependent: :destroy
end

app/models/bucket_list.rb
# frozen_string_literal: true

class BucketList < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bucket_list_tag_relations, dependent: :destroy
  has_many :tags, through: :bucket_list_tag_relations, dependent: :destroy

  # 一致するレコードが存在しない＝「まだいいねしていない→createアクションへ」
  # 一致するレコードが存在する　＝「すでにいいね済み→destroyアクションへ」
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索
  def self.looks(word)
    if word.blank?
      BucketList.all
    else
      BucketList.where("bucket_title LIKE?", "%#{word}%")
    end
  end

  # def save_tag(sent_tags)
  #   sent_tags.each do |new|
  #     new_bucket_list_tag = Tag.find_or_create_by(name: new)
  #     self.tags << new_bucket_list_tag
  #   end
  # end

  accepts_nested_attributes_for :bucket_list_tag_relations
  validates :memo, presence: true, length: { maximum: 140 }
end

app/models/bucket_list_tag_relation.rb
# frozen_string_literal: true

class BucketListTagRelation < ApplicationRecord
  belongs_to :bucket_list
  belongs_to :tag
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bucket_list

  validates :comment, presence: true, length: { maximum: 400 }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :bucket_list
  belongs_to :user
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :user
  has_many :scores
  has_many :records, through: :scores

  validates :player_name, length: { maximum: 12 }, presence: true
end

app/models/record.rb
# frozen_string_literal: true

class Record < ApplicationRecord
  belongs_to :user
  belongs_to :board_game
  has_many :scores
  has_many :players, through: :scores

  # score(子モデル)を保存するためのフォーム
  accepts_nested_attributes_for :scores, allow_destroy: true

  validates :memo, length: { maximum: 400 }
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  belongs_to :record
  belongs_to :player

  validates :score, numericality: {only_integer: true}
  
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :bucket_list_tag_relations, dependent: :destroy, foreign_key: "tag_id"
  has_many :bucket_lists, through: :bucket_list_tag_relations, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :board_games, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :bucket_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  # プロフィール画像
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-mage.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索
  def self.looks(word)
    if word.blank?
      User.all
    else
      User.where("name LIKE?", "%#{word}%")
    end
  end

  # ゲストユーザー
  def self.guest
    find_or_create_by!(name: "guestuser",
                      email: "guests@example.com",
                      postal_code: "1231234",
                      prefecture: "ボドゲ県",
                      city: "ミープル区",
                      age: "0〜99",
                      memo: "主に重ゲーを遊んでいます！") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  validates :postal_code, presence: true
  validates :name, uniqueness: true, length: { maximum: 12 }
  validates :city, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :postal_code, :prefecture, :city, :age])
    end

  private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_searches_path
      else
        root_path
      end
    end

    def
    after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
        root_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end
end

app/helpers/admin/searches_helper.rb
# frozen_string_literal: true

module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/player_helper.rb
# frozen_string_literal: true

module PlayerHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-success bg-opacity-75 text-white fixed-bottom">
  <div class="text-center">
    <p class="copyright m-0 fw-light">
      &copy; BoardGameRecorder
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <header class="shadow">
    <!--『navbar-expand-lg』レスポンシブ対応のため-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <% if admin_signed_in? %>
          <a class="navbar-brand" href="/admin/searches">BG録 BoardGameRecorder</a>
        <% else %>
          <a class="navbar-brand" href="/">BG録 BoardGameRecorder</a>
        <% end %>
        <!--ハンバーガーメニュー化-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!--devise機能リンク-->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <!--検索機能は左詰め-->
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "相手を探す", searches_path, class: 'nav-link active' %></li>
            <% end %>
          </ul>
          <!--ユーザー情報は右詰め-->
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= form_with url: search_searches_path, local: true, method: :get, class: "row" do |f| %>
                  <div class="input-group">
                    <div>
                      <%= f.text_field :word, class: "form-control",name: 'header_form', id: 'header_form', :placeholder => "ボードゲームを探す" %>
                    </div>
                  </div>
                <% end %>
              </li>
              <li class="nav-item ms-2">
                <%= link_to user_path(current_user) do %>
                  <%= image_tag current_user.get_profile_image(40,40) %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: 'nav-link active' do %>
                  <%= current_user.name %>
                <% end %>
              </li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link active' %></li>
            <% elsif admin_signed_in? %>
              <li class="nav-item"><%= link_to "タグ管理", new_admin_tag_path, method: :get, class: 'nav-link active' %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link active' %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "nav-link active", method: :post %></li>
              <li class="nav-item"><%= link_to "会員登録(なんとタダ)!", new_user_registration_path, class: 'nav-link active' %></li>
              <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: 'nav-link active' %></li>
            <% end %>
          </ul>
        </div>

      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BG6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="footerFixed">
    <body class="bg-warning bg-opacity-10">
      <%= render 'layouts/header' %>
      <div class="container mt-5 mb-5">
        <div class='row'>
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/footer' %>

      <script src="https://kit.fontawesome.com/c3f40df1c4.js" crossorigin="anonymous"></script>
    </body>
  </div>
</html>